// src/utils/welcomeTips.js
export const ALL_TIPS = [
  // Training / mindset (120)
  "Show up first; motivation can follow.",
  "One good set beats a perfect plan.",
  "Keep it simple: lift, breathe, repeat.",
  "Control the negative—strength lives there.",
  "Smooth reps > fast reps.",
  "Leave one rep in the tank on most sets.",
  "Add 1% today. That’s enough.",
  "Film one set to check your form.",
  "Warm up like it matters—because it does.",
  "Your best routine is the one you’ll repeat.",
  "Rest is part of training, not a break from it.",
  "Short session > skipped session.",
  "Chase consistency, not soreness.",
  "Brace like someone’s about to punch you.",
  "Strong posture makes strong reps.",
  "Make the first set the cleanest set.",
  "Slow down the last rep—own it.",
  "Drink water before you feel thirsty.",
  "You don’t need more time—just less scrolling.",
  "Technique now, PR later.",
  "Focus on range of motion, not ego.",
  "Start lighter, finish stronger.",
  "Train the movement, not the weight.",
  "If it hurts sharp, stop. If it burns, breathe.",
  "Track it—what gets measured gets better.",
  "Keep shoulders down and back on presses.",
  "Push the floor away on leg moves.",
  "“Good enough” beats “not today.”",
  "Two quality reps beat five messy ones.",
  "Eat protein like it’s a job.",
  "Sleep is your secret supplement.",
  "Small wins stack fast.",
  "Don’t rush the setup—setup is the lift.",
  "Strong core, strong everything.",
  "Treat warm-up sets as practice reps.",
  "Breathe out through the hard part.",
  "Keep your tempo honest.",
  "Avoid maxing out when you’re tired.",
  "Form first, weight second.",
  "If you’re stuck, add reps before weight.",
  "Your future self will thank you for today’s session.",
  "Lift with intent, not hope.",
  "Hit depth, then hit load.",
  "Pause reps build real strength.",
  "Less talk, more training.",
  "A bad day in the gym still counts.",
  "Train hard, recover harder.",
  "The bar doesn’t care—be consistent.",
  "Make your last set your best set.",
  "Keep a steady pace between sets.",
  "Set a timer; rest turns into doom-scrolling fast.",
  "Think “tight” before every rep.",
  "Don’t chase fatigue—chase progress.",
  "Strong hips, strong lifts.",
  "Pull with your elbows, not your hands.",
  "Save your back—hinge with purpose.",
  "If you can’t control it, it’s too heavy today.",
  "Your warm-up should raise temperature, not ego.",
  "One extra rep is a PR in disguise.",
  "Show discipline on light days too.",
  "The goal is to train again tomorrow.",
  "Stop comparing—start completing.",
  "Keep your feet planted like roots.",
  "Lock in your grip before you lift.",
  "Press the bench, don’t just lie on it.",
  "Move like an athlete, not a passenger.",
  "Keep your neck neutral; don’t crane.",
  "If you’re nervous, start with an easy win.",
  "Strong glutes protect your knees and back.",
  "If you can do more, leave a little for next time.",
  "Your logbook is your coach.",
  "Do the boring stuff—boring builds champions.",
  "Make today’s workout easy to repeat.",
  "Tight lats = stable presses and pulls.",
  "If you miss, reduce and rebuild—no drama.",
  "Don’t “test” strength every session—build it.",
  "Time under tension is still tension.",
  "Smooth breathing keeps reps cleaner.",
  "You’re one session away from momentum.",
  "Strong is a skill—practice it.",
  "Keep your warm-up consistent so progress is real.",
  "If you’re short on time, do the main lift only.",
  "Your pace should match your goal.",
  "Think “push the world away” on presses.",
  "Think “pull elbows to ribs” on rows.",
  "Add a rep, then add the plate.",
  "Start with your weakest lift while you’re freshest.",
  "A perfect week starts with one good day.",
  "Focus on the next rep, not the next month.",
  "Your confidence grows with completed workouts.",
  "Keep your wrists stacked and strong.",
  "Keep your ribs down when you press overhead.",
  "Get comfortable being uncomfortable—briefly.",
  "Tighten before you lift, relax after you rack.",
  "Hydrate, then caffeinate.",
  "Add steps on rest days; recovery loves movement.",
  "Don’t turn accessories into main lifts.",
  "Stop when form breaks, not when willpower does.",
  "Train for the person you want to be.",
  "Progress isn’t loud; it’s consistent.",
  "Long warm-up? Do fewer exercises, not none.",
  "If your head’s busy, count reps and breathe.",
  "The first 10 minutes decide the session—start.",
  "Keep rest times consistent for fair comparisons.",
  "When in doubt, do the next set.",
  "Strong legs make everything easier.",
  "If you’re fatigued, focus on perfect reps.",
  "Don’t skip mobility—earn your range.",
  "A lighter lift done right still builds muscle.",
  "Finish the session proud, not destroyed.",
  "Keep your spine long on hinges and squats.",
  "Slightly better form is still progress.",
  "Get the blood moving—then lift.",
  "Train with control; confidence follows.",
  "Your streak starts again the moment you return.",
  "One workout can change your whole week.",
  "Your body listens to what you repeat.",
  "Respect the basics; they work.",
  "Be patient—strength compounds.",
  "You don’t need perfect—just consistent.",

  // Nutrition (55)
  "Protein at every meal makes training easier.",
  "Eat to support tomorrow’s workout, not just today’s hunger.",
  "Carbs fuel performance—don’t fear them.",
  "A simple meal beats a skipped one.",
  "Hydration affects strength more than you think.",
  "Eat something within 2 hours post-workout.",
  "Protein shakes are tools, not magic.",
  "Whole foods first, supplements second.",
  "Consistency matters more than perfect macros.",
  "Fuel heavy days a little more.",
  "Under-eating slows progress fast.",
  "Don’t train hard on empty too often.",
  "Salt helps performance—especially if you sweat.",
  "Fruit counts. Veg counts. Both help recovery.",
  "Prep once, benefit all week.",
  "Hunger is feedback—listen to it.",
  "Eat slow enough to notice fullness.",
  "Protein supports recovery even on rest days.",
  "Liquid calories still count.",
  "A balanced plate beats restriction.",
  "Eat carbs earlier if you train later.",
  "Fibre helps digestion and consistency.",
  "Skipping meals increases cravings later.",
  "Fuel for performance, not punishment.",
  "Simple meals are easier to repeat.",
  "Food is training support, not the enemy.",
  "Eat enough to recover—not just survive.",
  "Plan meals like you plan workouts.",
  "Strength loves consistency, not extremes.",
  "Don’t chase fat loss at the cost of strength.",
  "A protein snack beats no snack.",
  "Water first—coffee second.",
  "Training fasted isn’t required for progress.",
  "Eat carbs on leg day—your body will thank you.",
  "Micronutrients matter long-term.",
  "Protein helps protect muscle in a deficit.",
  "Hunger during training hurts performance.",
  "Recovery starts with food.",
  "You don’t need fancy meals—just repeatable ones.",
  "Fuel before you feel flat.",
  "Calories are information, not judgment.",
  "Food quality improves recovery speed.",
  "Eat enough to train hard tomorrow.",
  "Strength gains need fuel.",
  "Don’t fear eating more when training more.",
  "A good meal is part of discipline.",
  "Eat like an athlete, not a dieter.",
  "One balanced day beats extremes all week.",
  "Recovery calories still count as progress.",
  "Food supports adaptation—use it.",

  // Recovery (55)
  "Recovery is where progress happens.",
  "Sleep is the best legal performance enhancer.",
  "Aim for consistency before duration.",
  "Go to bed earlier on training days.",
  "Quality sleep beats extra volume.",
  "Stretch what you train most.",
  "Light movement helps sore muscles recover.",
  "Rest days make hard days possible.",
  "Stress affects strength more than weight.",
  "Recovery is training you can’t skip.",
  "Walk more—your joints will thank you.",
  "Mobility keeps progress sustainable.",
  "Don’t stack fatigue for no reason.",
  "Sleep debt slows gains fast.",
  "Recovery lets effort turn into results.",
  "Train hard, rest with intent.",
  "Soreness isn’t required for growth.",
  "Consistent sleep beats weekend catch-up.",
  "Breath control helps nervous system recovery.",
  "Recovery quality affects next session quality.",
  "Take rest days seriously.",
  "Light stretching beats none.",
  "Your body adapts when rested.",
  "Fatigue hides strength.",
  "If joints ache, reduce volume—not effort.",
  "Stress management improves performance.",
  "Hydration helps recovery overnight.",
  "Sleep is non-negotiable for progress.",
  "A calm nervous system lifts better.",
  "Active recovery beats total inactivity.",
  "Respect signs of overreaching early.",
  "Recovery is cumulative—protect it.",
  "Don’t out-train poor sleep.",
  "Mobility keeps lifts pain-free.",
  "Deloads extend training careers.",
  "Warm muscles recover faster.",
  "Recovery supports long-term consistency.",
  "Recovery days still count.",
  "If performance drops, check sleep first.",
  "Relaxed breathing aids recovery.",
  "Strong routines include rest.",
  "Stress steals recovery resources.",
  "Recovery turns effort into adaptation.",
  "Protect your joints—they carry progress.",
  "Energy is a recovery signal.",
  "Sleep improves coordination and strength.",
  "Rest is a performance strategy.",
  "More isn’t always better—sometimes it’s worse.",
  "Recovery lets you train again tomorrow.",
  "Sustainable progress feels repeatable.",
  "Recovery supports longevity, not laziness.",
  "Train smart enough to stay training.",
  "Pain-free lifting is a win.",
  "Recovery makes strength reliable.",
  "Consistent recovery beats heroic effort.",
];